# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108Utpgji4-lQQJyMu0vws6M_EjnapEH7
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# plotly

import os
print(os.path.exists("requirements.txt"))

